### ISSUE TITLE
Ok to transfer back translations to the spreadsheet?

### ISSUE THREAD

**Issue by FossiFoo** [bani/101weiqiLocalizer#1]
Hi. Is it ok for you if I transfer back the improved translations into the spreadsheet that Clossi's chat made? https://docs.google.com/spreadsheets/d/1ixLr19YKZnu_uvocZbinRcBDM_qO1IML4t7cAD5Wpl8/edit#gid=0

**Comment by bani** [comment]
@FossiFoo sure, feel free to use what is in this repository it in any way you'd like, but keep in mind they aren't necessarily always improved. What you have here is a mix of what was on the original author's code, who I don't know how he came up with the translations, things I found on the spreadhseet and in some cases followed the Sensei's Library link to get more context about the term usage, and sometimes just Google translations that I tried to adapt to something that made sense in the context.

**Comment by bani** [comment]
I've copied all translations that are in the extension to a spreadsheet to make it easier to keep them sorted and allow people to leave comments if there is anything that needs to be changed.

It's available [here](https://docs.google.com/spreadsheets/d/1VGGhi-gUZ8tYWNyDaZnRfguxABbh1GESVkJT2pE-PP0/edit?usp=sharing).
